/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Bilgi.Personel;
import Bilgi.VeriTabaniIslemleri;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author hurud
 */
public class PersonelIslemleriView extends javax.swing.JFrame {
    
    DefaultTableModel model;
    VeriTabaniIslemleri veriTabani = new VeriTabaniIslemleri();
    
    
    
    

    /**
     * Creates new form PersonelIslemleriView
     */
    
    public void PersonelGoruntule(){
        model.setRowCount(0);
        
        ArrayList<Personel> personeller = new ArrayList<Personel>();
        
        personeller = veriTabani.personelGetir();
        
        if(personeller != null){
            for(Personel personel : personeller){
                Object[] eklenecek = {personel.getId(), personel.getPersonelAd(), personel.getPersonelSoyad(), personel.getEmail(), personel.getSifre(), personel.getDepartman()};
                
                model.addRow(eklenecek);
            }
        }
    }
    
    public PersonelIslemleriView() {
        initComponents();
        model = (DefaultTableModel)personelTable.getModel();
        PersonelGoruntule();
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personelIdLbl = new javax.swing.JLabel();
        personelAdLbl = new javax.swing.JLabel();
        soyisimLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        sifreLbl = new javax.swing.JLabel();
        departmanLbl = new javax.swing.JLabel();
        personelIdText = new javax.swing.JTextField();
        isimText = new javax.swing.JTextField();
        soyisimText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        sifreText = new javax.swing.JTextField();
        departmanText = new javax.swing.JTextField();
        personelEkleBtn = new javax.swing.JButton();
        personelGuncelleBtn = new javax.swing.JButton();
        personelSilBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        geriBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personelTable = new javax.swing.JTable();
        aramaCubuguText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        mesajLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Satış Stok Takip Sistemi");
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));

        personelIdLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        personelIdLbl.setText("Personel ID : ");

        personelAdLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        personelAdLbl.setText("İsim :");

        soyisimLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        soyisimLbl.setText("Soyisim : ");

        emailLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        emailLbl.setText("Email :");

        sifreLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        sifreLbl.setText("Şifre : ");

        departmanLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 13)); // NOI18N
        departmanLbl.setText("Departman : ");
        departmanLbl.setToolTipText("");

        personelIdText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N

        isimText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N

        soyisimText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N

        emailText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N

        sifreText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N

        departmanText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N

        personelEkleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        personelEkleBtn.setText("Personel Ekle");
        personelEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelEkleBtnActionPerformed(evt);
            }
        });

        personelGuncelleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        personelGuncelleBtn.setText("Personel Güncelle");
        personelGuncelleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelGuncelleBtnActionPerformed(evt);
            }
        });

        personelSilBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        personelSilBtn.setText("Personel Sil");
        personelSilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personelSilBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Personel İşlemleri");

        geriBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        geriBtn.setText("Geri");
        geriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriBtnActionPerformed(evt);
            }
        });

        personelTable.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        personelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Personel Ad", "Personel Soyad", "Email", "Şifre", "Departman"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personelTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personelTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personelTable);
        if (personelTable.getColumnModel().getColumnCount() > 0) {
            personelTable.getColumnModel().getColumn(0).setResizable(false);
            personelTable.getColumnModel().getColumn(1).setResizable(false);
            personelTable.getColumnModel().getColumn(2).setResizable(false);
            personelTable.getColumnModel().getColumn(3).setResizable(false);
            personelTable.getColumnModel().getColumn(4).setResizable(false);
            personelTable.getColumnModel().getColumn(5).setResizable(false);
        }

        aramaCubuguText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        aramaCubuguText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaCubuguTextKeyReleased(evt);
            }
        });

        mesajLbl.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(mesajLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aramaCubuguText)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personelIdLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sifreLbl)
                                    .addComponent(emailLbl)
                                    .addComponent(personelAdLbl)
                                    .addComponent(departmanLbl)
                                    .addComponent(soyisimLbl))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(departmanText)
                                    .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailText)
                                    .addComponent(personelIdText)
                                    .addComponent(isimText)
                                    .addComponent(soyisimText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personelGuncelleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(personelEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(personelSilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(aramaCubuguText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mesajLbl)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personelIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personelIdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isimText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personelAdLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soyisimText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soyisimLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sifreText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personelEkleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(personelGuncelleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(personelSilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmanText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departmanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriBtnActionPerformed

        YoneticiPanelView yoneticiPanel = new YoneticiPanelView();
        yoneticiPanel.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriBtnActionPerformed

    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tableRow = new TableRowSorter<DefaultTableModel>(model);
        
        personelTable.setRowSorter(tableRow);
        
        tableRow.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    private void aramaCubuguTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaCubuguTextKeyReleased

        String ara = aramaCubuguText.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_aramaCubuguTextKeyReleased

    private void personelEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelEkleBtnActionPerformed

        mesajLbl.setText("");
        
        String id = personelIdText.getText();
        String isim = isimText.getText();
        String soyisim = soyisimText.getText();
        String email = emailText.getText();
        String sifre = sifreText.getText();
        String departman = departmanText.getText();
        
        veriTabani.personelEkle(id,isim,soyisim,email,sifre,departman);
        
        PersonelGoruntule();
        
        mesajLbl.setText("Yeni personel başarıyla eklendi.");
        
    }//GEN-LAST:event_personelEkleBtnActionPerformed

    private void personelTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personelTableMouseClicked
        
        int selectedRow = personelTable.getSelectedRow();
        
        personelIdText.setText(model.getValueAt(selectedRow, 0).toString());
        isimText.setText(model.getValueAt(selectedRow, 1).toString());
        soyisimText.setText(model.getValueAt(selectedRow, 2).toString());
        emailText.setText(model.getValueAt(selectedRow, 3).toString());
        sifreText.setText(model.getValueAt(selectedRow, 4).toString());
        departmanText.setText(model.getValueAt(selectedRow, 5).toString());
        
    }//GEN-LAST:event_personelTableMouseClicked

    private void personelGuncelleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelGuncelleBtnActionPerformed
        
   
        String id = personelIdText.getText();
        String isim = isimText.getText();
        String soyisim = soyisimText.getText();
        String email = emailText.getText();
        String sifre = sifreText.getText();
        String departman = departmanText.getText();
        
        int selectedrow = personelTable.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesajLbl.setText("Personel tablosu şu anda boş");
            }
            else{
                mesajLbl.setText("Lütfen güncellenecek personel seçiniz");
            }
        }
        else{
            veriTabani.personelGuncelle(id,isim,soyisim,email,sifre,departman);
            PersonelGoruntule();
            mesajLbl.setText("Personel başarıyla güncellendi");
        }
        
    }//GEN-LAST:event_personelGuncelleBtnActionPerformed

    private void personelSilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personelSilBtnActionPerformed
        
        mesajLbl.setText("");
        
        int selectedrow = personelTable.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesajLbl.setText("Personel tablosu şu anda boş");
            }
            else{
                mesajLbl.setText("Lütfen silinecek bir personel seçiniz");
            }
        }
        else{
            int id = (int) model.getValueAt(selectedrow, 0);
            
            veriTabani.personelSil(id);
            
            PersonelGoruntule();
            mesajLbl.setText("Personel başarıyla silindi");
        }
        
    }//GEN-LAST:event_personelSilBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelIslemleriView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aramaCubuguText;
    private javax.swing.JLabel departmanLbl;
    private javax.swing.JTextField departmanText;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton geriBtn;
    private javax.swing.JTextField isimText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesajLbl;
    private javax.swing.JLabel personelAdLbl;
    private javax.swing.JButton personelEkleBtn;
    private javax.swing.JButton personelGuncelleBtn;
    private javax.swing.JLabel personelIdLbl;
    private javax.swing.JTextField personelIdText;
    private javax.swing.JButton personelSilBtn;
    private javax.swing.JTable personelTable;
    private javax.swing.JLabel sifreLbl;
    private javax.swing.JTextField sifreText;
    private javax.swing.JLabel soyisimLbl;
    private javax.swing.JTextField soyisimText;
    // End of variables declaration//GEN-END:variables
}
