/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Bilgi.Stok;
import Bilgi.VeriTabaniIslemleri;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hurud
 */
public class StokView extends javax.swing.JFrame {
    
    DefaultTableModel model;
    VeriTabaniIslemleri veriTabani = new VeriTabaniIslemleri();
    

    public void StokGoruntule(){
        model.setRowCount(0);
        
        ArrayList<Stok> stoklar = new ArrayList<Stok>();
        
        stoklar = veriTabani.stokGetir();
        
        if(stoklar != null){
            for(Stok stok : stoklar){
                Object[] eklenecek = {stok.getId(),stok.getUrunId(),stok.getSatilanMiktar(),stok.getAlinanMiktar()};
                
                model.addRow(eklenecek);
            }
        }
        
    }
    
    /**
     * Creates new form StokView
     */
    public StokView() {
        initComponents();
        model = (DefaultTableModel)stokTbl.getModel();
        StokGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stokTbl = new javax.swing.JTable();
        satilanLbl = new javax.swing.JLabel();
        alinanMiktarLbl = new javax.swing.JLabel();
        satilanMiktarText = new javax.swing.JTextField();
        alinanMiktarText = new javax.swing.JTextField();
        stokGuncelleBtn = new javax.swing.JButton();
        geriBtn = new javax.swing.JButton();
        mesajText = new javax.swing.JTextField();
        idLbl = new javax.swing.JLabel();
        urunIdLbl = new javax.swing.JLabel();
        urunIdText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        ekleBtn = new javax.swing.JButton();
        silBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Satış Stok Takip Sistemi");
        setBounds(new java.awt.Rectangle(600, 200, 0, 0));
        setPreferredSize(new java.awt.Dimension(675, 675));

        stokTbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        stokTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ürün ID", "Satılan Miktar", "Alınan Miktar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stokTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stokTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stokTbl);
        if (stokTbl.getColumnModel().getColumnCount() > 0) {
            stokTbl.getColumnModel().getColumn(0).setResizable(false);
            stokTbl.getColumnModel().getColumn(1).setResizable(false);
            stokTbl.getColumnModel().getColumn(2).setResizable(false);
            stokTbl.getColumnModel().getColumn(3).setResizable(false);
        }

        satilanLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        satilanLbl.setText("Satılan Miktar :");

        alinanMiktarLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        alinanMiktarLbl.setText("Alınan Miktar :");

        satilanMiktarText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        alinanMiktarText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        stokGuncelleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        stokGuncelleBtn.setText("Güncelle");

        geriBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        geriBtn.setText("Geri");
        geriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriBtnActionPerformed(evt);
            }
        });

        mesajText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        mesajText.setForeground(new java.awt.Color(255, 0, 51));

        idLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        idLbl.setText("ID :");

        urunIdLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        urunIdLbl.setText("Ürün ID :");

        urunIdText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        idText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });

        ekleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        ekleBtn.setText("Ekle");
        ekleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleBtnActionPerformed(evt);
            }
        });

        silBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        silBtn.setText("Sil");
        silBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Stok İşlemleri");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesajText, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(geriBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alinanMiktarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLbl)
                            .addComponent(satilanLbl)
                            .addComponent(urunIdLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(satilanMiktarText)
                            .addComponent(alinanMiktarText)
                            .addComponent(urunIdText)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(silBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ekleBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stokGuncelleBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mesajText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urunIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunIdLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(satilanMiktarText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(satilanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alinanMiktarText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alinanMiktarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ekleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stokGuncelleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriBtnActionPerformed
        UrunKategoriIslemleriView urunKategori = new UrunKategoriIslemleriView();
        urunKategori.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriBtnActionPerformed

    private void stokTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stokTblMouseClicked
        
        int selectedRow = stokTbl.getSelectedRow();
        idText.setText(model.getValueAt(selectedRow,0).toString());
        urunIdText.setText(model.getValueAt(selectedRow,1).toString());
        satilanMiktarText.setText(model.getValueAt(selectedRow, 2).toString());
        alinanMiktarText.setText(model.getValueAt(selectedRow, 3).toString());
    }//GEN-LAST:event_stokTblMouseClicked

    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tableRow = new TableRowSorter<DefaultTableModel>();
        stokTbl.setRowSorter(tableRow);
        tableRow.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void ekleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleBtnActionPerformed
        
        mesajText.setText("");
        
        String id = idText.getText();
        String urunId = urunIdText.getText();
        String satilanMiktar = satilanMiktarText.getText();
        String alinanMiktar = alinanMiktarText.getText();
        
        veriTabani.stokEkle(id,urunId,satilanMiktar,alinanMiktar);
        StokGoruntule();
        mesajText.setText("Yeni stok başarıyla eklendi.");
    }//GEN-LAST:event_ekleBtnActionPerformed

    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed
        
        mesajText.setText("");
        
        int selectedrow = stokTbl.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesajText.setText("Stok tablosu şu anda boş");
            }
            else{
                mesajText.setText("Lütfen silinecek bir stok seçiniz");
            }
        }
        else{
            int id = (int) model.getValueAt(selectedrow,0);
            
            veriTabani.stokSil(id);
            StokGoruntule();
            mesajText.setText("Stok başarıyla silindi");
        }
    }//GEN-LAST:event_silBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alinanMiktarLbl;
    private javax.swing.JTextField alinanMiktarText;
    private javax.swing.JButton ekleBtn;
    private javax.swing.JButton geriBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mesajText;
    private javax.swing.JLabel satilanLbl;
    private javax.swing.JTextField satilanMiktarText;
    private javax.swing.JButton silBtn;
    private javax.swing.JButton stokGuncelleBtn;
    private javax.swing.JTable stokTbl;
    private javax.swing.JLabel urunIdLbl;
    private javax.swing.JTextField urunIdText;
    // End of variables declaration//GEN-END:variables
}
