/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Bilgi.Urun;
import Bilgi.VeriTabaniIslemleri;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hurud
 */
public class UrunKategoriIslemleriView extends javax.swing.JFrame {
    
    DefaultTableModel model;
    VeriTabaniIslemleri veriTabani = new VeriTabaniIslemleri();
    


    /**
     * Creates new form UrunKategoriIslemleriView
     */
    
    public void UrunGoruntule(){
        model.setRowCount(0);
        
        ArrayList<Urun> urunler = new ArrayList<Urun>();
        
        urunler = veriTabani.urunGetir();
        
        if(urunler != null){
            for(Urun urun : urunler){
                Object[] eklenecek = {urun.getId(), urun.getKategoriId(), urun.getUrunAd(), urun.getMiktar(),urun.getFiyat()};
                
                model.addRow(eklenecek);
            }
        }
    }
    
    public UrunKategoriIslemleriView() {
        initComponents();
        model = (DefaultTableModel) urunTbl.getModel();
        UrunGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        silBtn1 = new javax.swing.JButton();
        geriBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        kategoriIdLbl = new javax.swing.JLabel();
        urunAdLbl = new javax.swing.JLabel();
        miktarLbl = new javax.swing.JLabel();
        fiyatLbl = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        urunAdText = new javax.swing.JTextField();
        miktarText = new javax.swing.JTextField();
        fiyatText = new javax.swing.JTextField();
        guncelleBtn = new javax.swing.JButton();
        ekleBtn = new javax.swing.JButton();
        silBtn = new javax.swing.JButton();
        stokGuncelleBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        urunTbl = new javax.swing.JTable();
        aramaCubuguText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        mesajLbl = new javax.swing.JLabel();
        kategoriText = new javax.swing.JTextField();
        mesaj2Lbl = new javax.swing.JLabel();

        silBtn1.setText("Ürün Sil");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Satış Stok Takip Sistemi");
        setBounds(new java.awt.Rectangle(425, 140, 0, 0));

        geriBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        geriBtn.setText("Geri");
        geriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Ürün İşlemleri");

        idLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        idLbl.setText("Ürün ID :");

        kategoriIdLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        kategoriIdLbl.setText("Kategori :");

        urunAdLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        urunAdLbl.setText("Ürün Adı :");

        miktarLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        miktarLbl.setText("Miktar :");

        fiyatLbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        fiyatLbl.setText("Fiyat :");

        idText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        urunAdText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        miktarText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        fiyatText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        guncelleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        guncelleBtn.setText("Ürün Güncelle");

        ekleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        ekleBtn.setText("Ürün Ekle");
        ekleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleBtnActionPerformed(evt);
            }
        });

        silBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        silBtn.setText("Ürün Sil");
        silBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silBtnActionPerformed(evt);
            }
        });

        stokGuncelleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 15)); // NOI18N
        stokGuncelleBtn.setText("Stok Güncelle");
        stokGuncelleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokGuncelleBtnActionPerformed(evt);
            }
        });

        urunTbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        urunTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kategori ID", "Ürün Ad", "Miktar", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        urunTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urunTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urunTbl);
        if (urunTbl.getColumnModel().getColumnCount() > 0) {
            urunTbl.getColumnModel().getColumn(0).setResizable(false);
            urunTbl.getColumnModel().getColumn(1).setResizable(false);
            urunTbl.getColumnModel().getColumn(2).setResizable(false);
            urunTbl.getColumnModel().getColumn(3).setResizable(false);
            urunTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        aramaCubuguText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        aramaCubuguText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaCubuguTextActionPerformed(evt);
            }
        });
        aramaCubuguText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaCubuguTextKeyReleased(evt);
            }
        });

        mesajLbl.setForeground(new java.awt.Color(255, 0, 0));

        kategoriText.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        kategoriText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriTextActionPerformed(evt);
            }
        });

        mesaj2Lbl.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        mesaj2Lbl.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mesajLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(311, 311, 311))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                            .addComponent(aramaCubuguText)
                            .addComponent(jSeparator1)
                            .addComponent(mesaj2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kategoriIdLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(urunAdLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(miktarLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fiyatLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(miktarText)
                                .addComponent(fiyatText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(urunAdText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kategoriText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stokGuncelleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(silBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ekleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addGap(39, 39, 39)
                .addComponent(aramaCubuguText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(mesaj2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesajLbl)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLbl)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kategoriText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kategoriIdLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urunAdText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunAdLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(miktarLbl)
                            .addComponent(miktarText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiyatText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiyatLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ekleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guncelleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(silBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stokGuncelleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriBtnActionPerformed

        YoneticiPanelView yoneticiPanel = new YoneticiPanelView();
        yoneticiPanel.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_geriBtnActionPerformed

    private void aramaCubuguTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaCubuguTextActionPerformed
    }//GEN-LAST:event_aramaCubuguTextActionPerformed

    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tableRow = new TableRowSorter<DefaultTableModel>(model);
        
        urunTbl.setRowSorter(tableRow);
        
        tableRow.setRowFilter(RowFilter.regexFilter(ara));
    }
    
    private void aramaCubuguTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaCubuguTextKeyReleased
        
        //klavyeden arama işlemi bitince getirir.
        
        String ara = aramaCubuguText.getText();
        
        dinamikAra(ara);
        
    }//GEN-LAST:event_aramaCubuguTextKeyReleased

    private void silBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silBtnActionPerformed
        
        mesaj2Lbl.setText("");
        
        int selectedrow = urunTbl.getSelectedRow();
        
        if(selectedrow == -1){
            if(model.getRowCount() == 0){
                mesaj2Lbl.setText("Ürün tablosu şu anda boş");
            }
            else{
                mesaj2Lbl.setText("Lütfen silinecek bir ürün seçiniz.");
            }
        }
        else{
            int id = (int) model.getValueAt(selectedrow, 0);
            
            veriTabani.urunSil(id);
            
            UrunGoruntule();
            mesaj2Lbl.setText("Ürün başarıyla silindi");
        }
    }//GEN-LAST:event_silBtnActionPerformed

    private void urunTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urunTblMouseClicked
        
               int selectedRow = urunTbl.getSelectedRow();
               
               idText.setText(model.getValueAt(selectedRow, 0).toString());
               kategoriText.setText(model.getValueAt(selectedRow, 1).toString());
               urunAdText.setText(model.getValueAt(selectedRow, 2).toString());
               miktarText.setText(model.getValueAt(selectedRow, 3).toString());
               fiyatText.setText(model.getValueAt(selectedRow, 4).toString());
         
          
          
    }//GEN-LAST:event_urunTblMouseClicked

    private void kategoriTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriTextActionPerformed

    private void stokGuncelleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokGuncelleBtnActionPerformed
        StokView stok = new StokView();
        stok.setVisible(true);
        dispose();
    }//GEN-LAST:event_stokGuncelleBtnActionPerformed

    private void ekleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleBtnActionPerformed
        
        mesaj2Lbl.setText("");
        
        String id = idText.getText();
        String kategoriId = kategoriText.getText();
        String urunAd = urunAdText.getText();
        String miktar = miktarText.getText();
        String fiyat = fiyatText.getText();
        
        veriTabani.urunEkle(id,kategoriId,urunAd,miktar,fiyat);
        
        UrunGoruntule();
        
        mesaj2Lbl.setText("Yeni ürün başarıyla eklendi.");
    }//GEN-LAST:event_ekleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunKategoriIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunKategoriIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunKategoriIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunKategoriIslemleriView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunKategoriIslemleriView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aramaCubuguText;
    private javax.swing.JButton ekleBtn;
    private javax.swing.JLabel fiyatLbl;
    private javax.swing.JTextField fiyatText;
    private javax.swing.JButton geriBtn;
    private javax.swing.JButton guncelleBtn;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kategoriIdLbl;
    private javax.swing.JTextField kategoriText;
    private javax.swing.JLabel mesaj2Lbl;
    private javax.swing.JLabel mesajLbl;
    private javax.swing.JLabel miktarLbl;
    private javax.swing.JTextField miktarText;
    private javax.swing.JButton silBtn;
    private javax.swing.JButton silBtn1;
    private javax.swing.JButton stokGuncelleBtn;
    private javax.swing.JLabel urunAdLbl;
    private javax.swing.JTextField urunAdText;
    private javax.swing.JTable urunTbl;
    // End of variables declaration//GEN-END:variables
}
